### ISSUE TITLE
Compile on server render?

### ISSUE THREAD

**Issue by lifeiscontent** [adambutler/riotjs-rails#5]
Is there a way with this gem to compile the riot tags on the server and serve the generated HTML?

**Comment by lifeiscontent** [comment]
@adambutler any updates??

**Comment by adambutler** [comment]
@lifeiscontent see #3

**Comment by lifeiscontent** [comment]
@adambutler this doesn't allow for serving it at HTML :-1:

**Comment by lifeiscontent** [comment]
https://www.youtube.com/watch?v=VKTWdaupft0&feature=youtu.be&t=14m28s
