### ISSUE TITLE
Gem directory empty after installation?

### ISSUE THREAD

**Issue by PandaWhisperer** [adambutler/riotjs-rails#7]
Hi,

I just tried installing this gem, and for some reason I kept getting this error, even though I had restarted my server:

```
Sprockets::FileNotFound at /
couldn't find file 'riotjs' with type 'application/javascript'
```

So I did a `ls $(bundle show riotjs-rails)` and it turns out the gem directory is completely empty. What's happening here?

**Comment by marcioj** [comment]
Hi @PandaWhisperer thanks for open the issue.
This is a pretty weird issue, looks like when downloading from rubygems the tarball is empty.

I tested here and using `gem 'riotjs-rails', github: 'adambutler/riotjs-rails'` in the Gemfile works fine.

Also running `gem build riotjs-rails.gemspec` from this project generates a `riotjs-rails-2.0.2.gem` with the correct file contents.

@adambutler can you please publish a new version to rubygems? I don't have permission to do so.

**Comment by adambutler** [comment]
Sorry for the slow reply. This is very odd. I've bumped the version and published. @marcioj please can you check this over.
